### ISSUE TITLE
What are AVS drivers?

### ISSUE THREAD

**Issue by paulmenzel** [chrultrabook/docs#73]
The instructions to install GNU/Linux contain the warning below:

https://github.com/chrultrabook/docs/blob/448ff37c1aa7e023fd9151f576d14d0a801ff1c8/docs/installing-linux.md?plain=1#L44

Unfortunately, I do not know what *AVS* is. The term is also mentioned in the FAQ, but from there it sounds like it’s a Windows driver?

> Can I get AVS or SOF drivers for free?
>    *   Only the Linux drivers are free.

**Comment by ellyq** [comment]
No, it's not a Windows driver. Windows drivers are based on Linux, that's why you usually see Linux getting support first, followed by Windows support.

It's a new kernelspace driver introduced by Intel's engineers, currently supporting SKL, KBL and APL.
We've been working with Intel's engineers on it for about a year. It's the only way to get properly working audio on Skylake and KabyLake platforms.
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/sound/soc/intel/avs

The reason why we can't modify the firmware is that Management Engine checks signature of DSP firmware we're trying to load. In case of ApolloLake for instance, we cannot load community-signed firmware. DSP FW has to be signed with Intel keys, otherwise it will fail to load.

**Comment by paulmenzel** [comment]
Thank you. From the [Linux Kconfig file](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/sound/soc/intel/Kconfig):

```
config SND_SOC_INTEL_AVS
	tristate "Intel AVS driver"
	depends on X86 || COMPILE_TEST
	depends on PCI
	depends on COMMON_CLK
	select SND_SOC_ACPI if ACPI
	select SND_SOC_TOPOLOGY
	select SND_SOC_HDA
	select SND_SOC_COMPRESS if DEBUG_FS
	select SND_HDA_EXT_CORE
	select SND_HDA_DSP_LOADER
	select SND_INTEL_DSP_CONFIG
	select WANT_DEV_COREDUMP
	help
	  Enable support for Intel(R) cAVS 1.5 platforms with DSP
	  capabilities. This includes Skylake, Kabylake, Amberlake and
	  Apollolake.
```

Luckily, Alder Lake does not seem to be “affected”.

**Comment by ellyq** [comment]
No, CometLake, TigerLake and AlderLake uses Sound Open Firmware. Same for GeminiLake and to some point ApolloLake (although with issues).

I have KOHAKU and ELDRID here, both using MAX98357A, working perfectly. In fact, we've tested those platforms with thermal cameras, oscilloscope and volume meter to fine-tune it on mainline.

**Comment by micvb123** [comment]
I have a RABBID (Apollolake) with its EOL approaching this summer, was thinking of linuxing it then -  hoping the sd card detection can be fixed by then.
